version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_AUTH_API=/api/auth
      - REACT_APP_PROFILE_API=/api/profiles
      - REACT_APP_PROJECT_API=/api/projects
    depends_on:
      db:
        condition: service_healthy
      auth_service:
        condition: service_started
      user_profile_service:
        condition: service_started
      project_service:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped

  auth_service:
    build: ./auth_service
    expose:
      - "8000"
    environment:
      - SECRET_KEY=your-secret-key
      - DATABASE_URL=postgresql://postgres:password@db:5432/auth_db
    volumes:
      - ./auth_service:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  user_profile_service:
    build: ./user_profile_service
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/profile_db
    volumes:
      - ./user_profile_service:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  project_service:
    build: ./project_service
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/project_db
    volumes:
      - ./project_service:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
